// components/SummaryPanel.jsx

import { Badge } from "./Badge";
import { TOPIC_STYLES } from "../constants";

function Section({ title, items, icon }) {
  return (
    <div style={{ marginBottom: 20 }}>
      <div style={{ display: "flex", alignItems: "center", gap: 6, marginBottom: 8 }}>
        <i className={`ti ${icon}`} style={{ fontSize: 16, color: "#7C3AED" }} aria-hidden />
        <h3 style={{ margin: 0, fontSize: 14, fontWeight: 600, color: "#1E293B" }}>{title}</h3>
      </div>
      {items.length === 0 ? (
        <p style={{ fontSize: 13, color: "#94A3B8", margin: 0 }}>None captured</p>
      ) : (
        items.map((item, i) => (
          <div
            key={i}
            style={{
              fontSize: 13, padding: "6px 12px", marginBottom: 4,
              background: "#F8FAFC", borderRadius: 8, color: "#334155",
              borderLeft: "3px solid #7C3AED",
            }}
          >
            {typeof item === "string" ? item : item.content}
          </div>
        ))
      )}
    </div>
  );
}

export function SummaryPanel({ summary, onClose }) {
  if (!summary) return null;

  return (
    <div
      style={{
        position: "fixed", inset: 0, background: "rgba(0,0,0,0.4)",
        display: "flex", alignItems: "center", justifyContent: "center",
        zIndex: 100, padding: 20,
      }}
    >
      <div
        style={{
          background: "white", borderRadius: 16, padding: 28,
          maxWidth: 600, width: "100%", maxHeight: "85vh",
          overflowY: "auto", boxShadow: "0 20px 60px rgba(0,0,0,0.15)",
        }}
      >
        {/* Header */}
        <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 20 }}>
          <div>
            <h2 style={{ margin: 0, fontSize: 20, fontWeight: 700, color: "#1E293B" }}>
              Session Summary
            </h2>
            <p style={{ margin: "4px 0 0", fontSize: 13, color: "#64748B" }}>
              Generated by MindBridge NLP
            </p>
          </div>
          <button
            onClick={onClose}
            style={{
              background: "none", border: "1px solid #E2E8F0",
              borderRadius: 8, padding: "6px 10px",
              cursor: "pointer", color: "#64748B",
            }}
          >
            <i className="ti ti-x" style={{ fontSize: 16 }} />
          </button>
        </div>

        <Section title="Key Points"           items={summary.key_points}           icon="ti-star" />
        <Section title="Unresolved Questions" items={summary.unresolved_questions} icon="ti-help-circle" />
        <Section title="Action Items"         items={summary.action_items}         icon="ti-checkbox" />
        <Section title="Next Steps"           items={summary.next_steps}           icon="ti-arrow-right" />

        {/* Topic distribution */}
        {summary.topic_clusters?.length > 0 && (
          <div>
            <div style={{ display: "flex", alignItems: "center", gap: 6, marginBottom: 8 }}>
              <i className="ti ti-chart-bar" style={{ fontSize: 16, color: "#7C3AED" }} aria-hidden />
              <h3 style={{ margin: 0, fontSize: 14, fontWeight: 600, color: "#1E293B" }}>
                Topic Distribution
              </h3>
            </div>
            <div style={{ display: "flex", flexWrap: "wrap", gap: 8 }}>
              {summary.topic_clusters.map((c, i) => {
                const s = TOPIC_STYLES[c.topic] || TOPIC_STYLES.general;
                return (
                  <Badge
                    key={i}
                    label={`${c.topic} (${c.count})`}
                    style={{ background: s.bg, color: s.text, border: `1px solid ${s.border}`, fontSize: 12 }}
                  />
                );
              })}
            </div>
          </div>
        )}
      </div>
    </div>
  );
}